replicaCount: 1
image:
  repository: 730335383329.dkr.ecr.us-east-1.amazonaws.com/cybersapient-ecr-repo
  tag: nonprod-develop
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: "0.25"
    memory: "512Mi"
  limits:
    cpu: "0.25"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60