replicaCount: 3

image:
  repository: 730335383328.dkr.ecr.us-east-1.amazonaws.com/cybersapient-ecr-repo
  tag: prod-main
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

namespace: prod
