replicaCount: 1
image:
  repository: 730335383329.dkr.ecr.us-east-1.amazonaws.com/cybersapient-ecr-repo
  tag: prod-main
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
resources:
  requests:
    cpu: "0.5"
    memory: "1024Mi"
  limits:
    cpu: "0.5"
    memory: "1024Mi"
